name: Deploy to Cloudflare Pages

on:
  schedule:
    - cron: '*/25 * * * *' # 每20分钟执行一次
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup WARP
        run: |
         echo "WARP mode: client warp+doh."
         sudo apt-get -y update
         curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
         echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
         sudo apt-get update
         sudo apt-get install -y cloudflare-warp
         sudo warp-cli --accept-tos registration new
         sudo warp-cli --accept-tos mode warp+doh
         if [ "${{ inputs.stack }}" == 'ipv4' ]; then
           sudo warp-cli --accept-tos add-excluded-route ::/0
         elif [ "${{ inputs.stack }}" == 'ipv6' ]; then
           sudo warp-cli --accept-tos add-excluded-route 0.0.0.0/0
         fi
         sudo warp-cli --accept-tos connect

         sleep 1
         echo "IPv4: $(sudo curl -s4m8 --retry 3 -A Mozilla https://api.ip.sb/geoip)"
         echo "IPv6: $(sudo curl -s6m8 --retry 3 -A Mozilla https://api.ip.sb/geoip)"


      - name: Cloudflare pages build
        uses: Cyb3r-Jak3/actions-cloudflare-pages@v2.0.0
        with:
         account: ${{ secrets.CLOUDFLARE_ZONE }}
         project: ${{ secrets.CLOUDFLARE_PROJECT }}
         email: ${{ secrets.CLOUDFLARE_EMAIL }}
         global_token: ${{ secrets.CLOUDFLARE_KEY }}
